# Generated by Django 5.2.3 on 2026-02-04 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_comment_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created']},
        ),
    ]
